#!/usr/bin/env python3
"""Generate database/seed.sql from NCPA_Inventory_All.xlsx for the current schema.

Seeds:
  1. Venues (6 home venues with full names, explicit ids 1-6).
  2. Crew members (12 real NCPA names; Ashwin = head).
  3. Equipment (one row per distinct model name, explicit ids 1..N).
  4. Items (one row per physical unit, item_number 001..NNN per model, spread
     across venues per the Excel quantities).

Uses explicit ids everywhere so items reference equipment by id rather than
subquery-by-name, which lets all item inserts fit in a single multi-VALUES
statement.
"""
from pathlib import Path
import openpyxl

ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / "NCPA_Inventory_All.xlsx"
OUT = ROOT / "database" / "seed.sql"

VENUES = [
    (1, "JBT Theatre", "JBT"),
    (2, "Tata Theatre", "TATA"),
    (3, "Experimental Theatre", "TET"),
    (4, "Little Theatre", "LT"),
    (5, "Godrej Dance Theatre", "GDT"),
    (6, "Office Store", "OFFICE"),
]
VENUE_COL = ["JBT", "TATA", "TET", "LT", "GDT", "OFFICE"]

CREW = [
    ("Naren", "crew"),
    ("Coni", "crew"),
    ("Sandeep", "crew"),
    ("Nikhil", "crew"),
    ("Aditya", "crew"),
    ("NS", "crew"),
    ("Nazar", "crew"),
    ("Shridhar", "crew"),
    ("Omkar", "crew"),
    ("Viraj", "crew"),
    ("Akshay", "crew"),
    ("Ashwin", "head"),
]


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb["ALL EQUIPMENT"]

    rows = []
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0:
            continue
        if row[0] is None or isinstance(row[0], str):
            continue
        _, name, cat, jbt, tata, tet, lt, gdt, office, _total = row
        if not name or not cat:
            continue
        name = str(name).strip()
        cat = str(cat).strip()
        qty = {
            "JBT": int(jbt or 0),
            "TATA": int(tata or 0),
            "TET": int(tet or 0),
            "LT": int(lt or 0),
            "GDT": int(gdt or 0),
            "OFFICE": int(office or 0),
        }
        rows.append((name, cat, qty))

    out = []
    out.append("-- Generated by src/scripts/build_seed.py — do not edit by hand.\n\n")

    out.append("-- Venues (explicit ids so items FK is stable).\n")
    venue_values = ",".join(
        f"({vid}, {sql_str(name)}, {sql_str(code)})" for vid, name, code in VENUES
    )
    out.append(f"INSERT OR IGNORE INTO venues (id, name, description) VALUES {venue_values};\n")

    out.append("\n-- Crew members\n")
    crew_values = ",".join(
        f"({sql_str(name)}, {sql_str(role)})" for name, role in CREW
    )
    out.append(f"INSERT OR IGNORE INTO crew_members (name, role) VALUES {crew_values};\n")

    out.append("\n-- Equipment (explicit ids so items FK is stable).\n")
    equipment_values = ",".join(
        f"({i + 1}, {sql_str(name)}, {sql_str(cat)})" for i, (name, cat, _q) in enumerate(rows)
    )
    out.append(
        f"INSERT OR IGNORE INTO equipment (id, name, category) VALUES {equipment_values};\n"
    )

    out.append("\n-- Items (one row per physical unit).\n")
    item_value_tuples = []
    for eq_id, (_name, _cat, qty) in enumerate(rows, start=1):
        serial = 0
        for code in VENUE_COL:
            n = qty.get(code, 0)
            venue_id = next(v[0] for v in VENUES if v[2] == code)
            for _ in range(n):
                serial += 1
                item_number = f"{serial:03d}"
                item_value_tuples.append(
                    f"({eq_id}, {sql_str(item_number)}, {venue_id}, {venue_id}, 'available')"
                )
    # Split items into chunks of 500 to keep individual statements manageable.
    chunk = 500
    for i in range(0, len(item_value_tuples), chunk):
        vals = ",".join(item_value_tuples[i : i + chunk])
        out.append(
            "INSERT OR IGNORE INTO items "
            f"(equipment_id, item_number, home_venue_id, current_venue_id, status) VALUES {vals};\n"
        )

    OUT.write_text("".join(out))
    total_items = sum(n for _, _, q in rows for n in q.values())
    print(f"Wrote {OUT} — {len(rows)} equipment, {total_items} items.")


if __name__ == "__main__":
    main()
