#!/usr/bin/env python3
"""Generate db/seed.sql from NCPA_Inventory_All.xlsx.

Reads the workbook, emits SQL that:
  1. Inserts venues (JBT, TATA, TET, LT, GDT, OFFICE).
  2. Inserts crew members (12 names; Ashwin = head).
  3. Inserts equipment_models (one row per distinct model).
  4. Inserts individual items: for each model with quantity N at venue V,
     emits N rows with serial_no 1..N and home_venue_id = V, all initially
     resident at their home venue.

Re-run safe: uses INSERT OR IGNORE for static rows, but the items section is
guarded by an existence check at the top of seed.sql.
"""
import base64
import hashlib
import os
import secrets
import openpyxl
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XLSX = ROOT / "NCPA_Inventory_All.xlsx"
OUT = ROOT / "db" / "seed.sql"

# Initial admin password (used only on first deploy; admin can rotate via UI).
INITIAL_ADMIN_PASSWORD = os.environ.get("INITIAL_ADMIN_PASSWORD", "Lsi@123456")
PBKDF2_ITERS = 100_000


def pbkdf2_hash(password: str) -> str:
    salt = secrets.token_bytes(16)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PBKDF2_ITERS, 32)
    return f"pbkdf2$sha256${PBKDF2_ITERS}${base64.b64encode(salt).decode()}${base64.b64encode(dk).decode()}"


def random_signing_key() -> str:
    return base64.b64encode(secrets.token_bytes(32)).decode()

VENUES = [
    ("JBT Theatre", "JBT", 0),
    ("Tata Theatre", "TATA", 0),
    ("Experimental Theatre", "TET", 0),
    ("Little Theatre", "LT", 0),
    ("Godrej Dance Theatre", "GDT", 0),
    ("Office Store", "OFFICE", 0),
]
VENUE_COL = ["JBT", "TATA", "TET", "LT", "GDT", "OFFICE"]

CREW = [
    ("Naren", "member"),
    ("Coni", "member"),
    ("Sandeep", "member"),
    ("Nikhil", "member"),
    ("Aditya", "member"),
    ("NS", "member"),
    ("Nazar", "member"),
    ("Shridhar", "member"),
    ("Omkar", "member"),
    ("Viraj", "member"),
    ("Akshay", "member"),
    ("Ashwin", "head"),
]


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb["ALL EQUIPMENT"]

    rows = []
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0:
            continue
        if row[0] is None or isinstance(row[0], str):
            # category header row
            continue
        _, name, cat, jbt, tata, tet, lt, gdt, office, _total = row
        if not name or not cat:
            continue
        name = str(name).strip()
        cat = str(cat).strip()
        qty = {
            "JBT": int(jbt or 0),
            "TATA": int(tata or 0),
            "TET": int(tet or 0),
            "LT": int(lt or 0),
            "GDT": int(gdt or 0),
            "OFFICE": int(office or 0),
        }
        rows.append((name, cat, qty))

    out = []
    out.append("-- Generated by scripts/build_seed.py — do not edit by hand.\n")
    out.append("PRAGMA foreign_keys = ON;\n\n")

    out.append("-- Venues\n")
    for name, code, outdoor in VENUES:
        out.append(
            f"INSERT OR IGNORE INTO venues (name, code, is_outdoor) VALUES "
            f"({sql_str(name)}, {sql_str(code)}, {outdoor});\n"
        )

    out.append("\n-- Settings (admin password hash + token signing key).\n")
    out.append("-- INSERT OR IGNORE so re-running the seed does not reset the admin password.\n")
    out.append(
        "INSERT OR IGNORE INTO settings (key, value) VALUES "
        f"('admin_password_hash', {sql_str(pbkdf2_hash(INITIAL_ADMIN_PASSWORD))});\n"
    )
    out.append(
        "INSERT OR IGNORE INTO settings (key, value) VALUES "
        f"('token_signing_key', {sql_str(random_signing_key())});\n"
    )

    out.append("\n-- Crew\n")
    for name, role in CREW:
        out.append(
            f"INSERT OR IGNORE INTO crew (name, role) VALUES "
            f"({sql_str(name)}, {sql_str(role)});\n"
        )

    out.append("\n-- Equipment models\n")
    for name, cat, _qty in rows:
        out.append(
            f"INSERT OR IGNORE INTO equipment_models (name, category) VALUES "
            f"({sql_str(name)}, {sql_str(cat)});\n"
        )

    out.append("\n-- Individual items (one row per physical unit).\n")
    out.append("-- Skip entirely if items already exist (idempotent re-seed).\n")

    # We can't easily do conditional-insert in SQLite without procedural code,
    # so we wrap each item insert with a NOT EXISTS guard. Cheaper approach:
    # use INSERT OR IGNORE relying on UNIQUE(model_id, serial_no).
    # Serial numbers must be unique per model across all venues — keep a
    # running counter per model and advance through every venue.
    for name, _cat, qty in rows:
        serial = 0
        for code in VENUE_COL:
            n = qty.get(code, 0)
            for _ in range(n):
                serial += 1
                label = f"{name} #{serial:03d}"
                out.append(
                    "INSERT OR IGNORE INTO items "
                    "(model_id, serial_no, label, home_venue_id, current_venue_id) "
                    "SELECT m.id, "
                    f"{serial}, "
                    f"{sql_str(label)}, "
                    "v.id, v.id "
                    "FROM equipment_models m, venues v "
                    f"WHERE m.name = {sql_str(name)} AND v.code = {sql_str(code)};\n"
                )

    OUT.write_text("".join(out))
    total_items = sum(n for _, _, q in rows for n in q.values())
    print(f"Wrote {OUT} — {len(rows)} models, {total_items} items.")


if __name__ == "__main__":
    main()
